spring:
    application:
        name: spring-practice-reactive-mongo

    data:
        mongodb:
            uri: ${MONGODB_URL}
            database: ${MONGODB_DATABASE}

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${OAUTH2_ISSUER_URI}

logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            ReactiveMongoTemplate: DEBUG