spring:
    application:
        name: spring-practice-reactive-mongo

    data:
        mongodb:
            uri: ${MONGODB_URL}
            database: ${MONGODB_DATABASE}

logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            ReactiveMongoTemplate: DEBUG